-- Generated by the database client.
CREATE TABLE "User"(
    id SERIAL NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    role "Role" NOT NULL DEFAULT 'USER'::"Role",
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX "User_email_key" ON public."User" USING btree (email);